<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <BaseIntermediateOutputPath>obj/Sim/</BaseIntermediateOutputPath>
    <BaseOutputPath>bin/Sim/</BaseOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="PogoDom.Core.Headless.csproj" />
  </ItemGroup>
</Project>
